# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CombellCli < Formula
  desc "CLI tool for the Combell API"
  homepage "https://github.com/nightlybuildsco/combell-cli"
  version "1.0.0-beta1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v1.0.0-beta1/combell-cli_1.0.0-beta1_darwin_amd64.tar.gz"
      sha256 "0b32f2ed1733df1ad375da35aba109b774482c188c12e03b6c4fb3bb6e263ecd"

      define_method(:install) do
        bin.install "combell-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v1.0.0-beta1/combell-cli_1.0.0-beta1_darwin_arm64.tar.gz"
      sha256 "f523f3e7211883dcdb4359e3ace13f1bc0bdfabad66486c470d3251acdaa19eb"

      define_method(:install) do
        bin.install "combell-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v1.0.0-beta1/combell-cli_1.0.0-beta1_linux_amd64.tar.gz"
      sha256 "1018b99c3006df0078bf747906364bd915c131ba2a6e1ee670a43bda4bf98a94"
      define_method(:install) do
        bin.install "combell-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v1.0.0-beta1/combell-cli_1.0.0-beta1_linux_arm64.tar.gz"
      sha256 "16a746e3711b85b0041e7f0b38b05f78d088f324dc18ed48bba3085a301913e8"
      define_method(:install) do
        bin.install "combell-cli"
      end
    end
  end
end
