# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CombellCli < Formula
  desc "CLI tool for the Combell API"
  homepage "https://github.com/nightlybuildsco/combell-cli"
  version "1-beta1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v1-beta1/combell-cli_1-beta1_darwin_amd64.tar.gz"
      sha256 "9bf6fa6173d0d6c2df06f3d5f500a41de65fd3575c4df8c2a5fdf064ca5cc0ca"

      define_method(:install) do
        bin.install "combell-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v1-beta1/combell-cli_1-beta1_darwin_arm64.tar.gz"
      sha256 "552e1784c7d65e475936698ca43fa41951f072aa477729229259e3966137393e"

      define_method(:install) do
        bin.install "combell-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v1-beta1/combell-cli_1-beta1_linux_amd64.tar.gz"
      sha256 "1465606b8eb76eb5a3b1b8b63600f1e30748331b1c3c1220feb54907b222eee9"
      define_method(:install) do
        bin.install "combell-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v1-beta1/combell-cli_1-beta1_linux_arm64.tar.gz"
      sha256 "4372096158df204f825e8c3570cb39bcdb4d3f680d40b711938c5b86f0906464"
      define_method(:install) do
        bin.install "combell-cli"
      end
    end
  end
end
