# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DataforseoCli < Formula
  desc "CLI tool for the DataForSEO API"
  homepage "https://github.com/nightlybuildsco/dataforseo-cli"
  version "1.0.0-beta1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta1/dataforseo-cli_1.0.0-beta1_darwin_amd64.tar.gz"
      sha256 "654200ad25ccd0cf32d9aa3d751f033333d32458d56363d62bf3084c053fce0f"

      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta1/dataforseo-cli_1.0.0-beta1_darwin_arm64.tar.gz"
      sha256 "2d2d3c06e5e2768835c55b8f873cfb837d09fca737b787d90493db3d77532b6d"

      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta1/dataforseo-cli_1.0.0-beta1_linux_amd64.tar.gz"
      sha256 "343575734757350db797a3bd328aa6845513ea73c2cf3e9e9da97368deeb20f3"
      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta1/dataforseo-cli_1.0.0-beta1_linux_arm64.tar.gz"
      sha256 "d3ef1f834e302b87c067675643d761be00aac5f740d34f5795642115940df69b"
      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
  end
end
