# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DataforseoCli < Formula
  desc "CLI tool for the DataForSEO API"
  homepage "https://github.com/nightlybuildsco/dataforseo-cli"
  version "1.0.0-beta2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta2/dataforseo-cli_1.0.0-beta2_darwin_amd64.tar.gz"
      sha256 "29e3e3ec65ba0ee2793dc252cbb00457b7e88ac6f78d0b3062d1e3d9c1aa55b2"

      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta2/dataforseo-cli_1.0.0-beta2_darwin_arm64.tar.gz"
      sha256 "63790ec066fdf18fbd584b98c52105c82e021022c19452874ff6a228417c6e33"

      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta2/dataforseo-cli_1.0.0-beta2_linux_amd64.tar.gz"
      sha256 "1b25a58ae3df64e80bd9876aa71431456b4e36a9a4a10d45c4d208a0f6397a8b"
      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta2/dataforseo-cli_1.0.0-beta2_linux_arm64.tar.gz"
      sha256 "a76a7f958ed283a782dcfd60230ab5b173d2b0412aaabeacf075ca8c980fa469"
      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
  end
end
