# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DataforseoCli < Formula
  desc "CLI tool for the DataForSEO API"
  homepage "https://github.com/nightlybuildsco/dataforseo-cli"
  version "1.0.0-beta1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta1/dataforseo-cli_1.0.0-beta1_darwin_amd64.tar.gz"
      sha256 "2f9bc58271a984e9aee59beb0e2b9b860642366ee8ee05403ac64f1c35ecc351"

      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta1/dataforseo-cli_1.0.0-beta1_darwin_arm64.tar.gz"
      sha256 "9647ccf6c6edae22f4da2ad4d7112f055eb777d868d0e90d5bbd1cfb34a684ea"

      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta1/dataforseo-cli_1.0.0-beta1_linux_amd64.tar.gz"
      sha256 "6190a9377b23e1ff06d5b90ee6d5e8d1dead77a4f29ce61cb20a161872cc9041"
      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/dataforseo-cli-releases/releases/download/v1.0.0-beta1/dataforseo-cli_1.0.0-beta1_linux_arm64.tar.gz"
      sha256 "13752c963eeb6ee27fa784d8a09cf679d2adcc36cd70e50a29f83f4dd93a9a0a"
      define_method(:install) do
        bin.install "dataforseo-cli"
      end
    end
  end
end
