# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MarketoCli < Formula
  desc "CLI tool for the Marketo REST API"
  homepage "https://github.com/nightlybuildsco/marketo-cli"
  version "1.0.0-beta1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nightlybuildsco/marketo-cli-releases/releases/download/v1.0.0-beta1/marketo-cli_1.0.0-beta1_darwin_amd64.tar.gz"
      sha256 "fda6c978b2ed5630e5833b2d5835c3007e5bfa5150ae0ae3f4d63e065914d057"

      define_method(:install) do
        bin.install "marketo-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nightlybuildsco/marketo-cli-releases/releases/download/v1.0.0-beta1/marketo-cli_1.0.0-beta1_darwin_arm64.tar.gz"
      sha256 "a31387a9ed9ef206cea221923e024389d6e433377d6cd5174abf3542b647aff5"

      define_method(:install) do
        bin.install "marketo-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/marketo-cli-releases/releases/download/v1.0.0-beta1/marketo-cli_1.0.0-beta1_linux_amd64.tar.gz"
      sha256 "d2e4666149e840ea8088d0fdff7715770bc24bbda05a1c9b49b6fad958fa801a"
      define_method(:install) do
        bin.install "marketo-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightlybuildsco/marketo-cli-releases/releases/download/v1.0.0-beta1/marketo-cli_1.0.0-beta1_linux_arm64.tar.gz"
      sha256 "70f211fddbfc4e5583bb8218097516f3f65860b9459a5dd6a7bfad66d1d86d9f"
      define_method(:install) do
        bin.install "marketo-cli"
      end
    end
  end
end
