# This file was generated by GoReleaser. DO NOT EDIT.
cask "combell-cli" do
  name "combell-cli"
  desc "CLI tool for the Combell API"
  homepage "https://github.com/nightlybuildsco/combell-cli"
  version "1-beta1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "combell-cli"

  on_macos do
    on_intel do
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v#{version}/combell-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "3092b4fb37036b39eda487d0e25b4116219e3b3f727ed328642420184ca92b9e"
    end
    on_arm do
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v#{version}/combell-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "f2d230b195c9ce3f0700e7fe86221d29e9385c493c0300f79da9e85662dbe6f4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v#{version}/combell-cli_#{version}_linux_amd64.tar.gz"
      sha256 "5d4826a2e8abfe79871c4557fe856c52dafb9e8c3291a2428b535f0ea4347260"
    end
    on_arm do
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v#{version}/combell-cli_#{version}_linux_arm64.tar.gz"
      sha256 "774dc108dc8fc7f98dc817f1d946182312e306ef0c4444a8edb31b9520ea1d95"
    end
  end

  # No zap stanza required
end
