# This file was generated by GoReleaser. DO NOT EDIT.
cask "combell-cli-releases" do
  name "combell-cli-releases"
  desc "CLI tool for the Combell API"
  homepage "https://github.com/nightlybuildsco/combell-cli"
  version "1-beta1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "combell-cli-releases"

  on_macos do
    on_intel do
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v#{version}/combell-cli-releases_#{version}_darwin_amd64.tar.gz"
      sha256 "92f0534a02d10b658fadb3254c5c0b61adff466dc5febe3a1ae1555bdd5a016d"
    end
    on_arm do
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v#{version}/combell-cli-releases_#{version}_darwin_arm64.tar.gz"
      sha256 "2e322ea5af34eca519f4074bc6d304ca2a5e1aad89c6352c790ffc876a205721"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v#{version}/combell-cli-releases_#{version}_linux_amd64.tar.gz"
      sha256 "6c547c30e808cf1626a5569d2a98d0d78621c4640ce42bda6c32410cee089024"
    end
    on_arm do
      url "https://github.com/nightlybuildsco/combell-cli-releases/releases/download/v#{version}/combell-cli-releases_#{version}_linux_arm64.tar.gz"
      sha256 "119fbf17aa3f8eac9a315d39a974bc60d7154ab547f33362939e0e060685b179"
    end
  end

  # No zap stanza required
end
