# This file was generated by GoReleaser. DO NOT EDIT.
cask "combell-cli" do
  name "combell-cli"
  desc "CLI tool for the Combell API"
  homepage "https://github.com/nightlybuildsco/combell-cli"
  version "1-beta1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "combell-cli"

  on_macos do
    on_intel do
      url "https://github.com/nightlybuildsco/combell-cli/releases/download/v#{version}/combell-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "7c702efd738a1ff4430afd3e77d1ac3efcb275042ba29eef44995601cb8091ec"
    end
    on_arm do
      url "https://github.com/nightlybuildsco/combell-cli/releases/download/v#{version}/combell-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "b6916126ab234b7262193a7091665cd4236d6975b5628c8ffe122a669a01318c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nightlybuildsco/combell-cli/releases/download/v#{version}/combell-cli_#{version}_linux_amd64.tar.gz"
      sha256 "a7fb03e4112b4d9f92d840dd93831a0239eb157a5ffdda080d5196dc73cc6fa3"
    end
    on_arm do
      url "https://github.com/nightlybuildsco/combell-cli/releases/download/v#{version}/combell-cli_#{version}_linux_arm64.tar.gz"
      sha256 "280ef700f1321ddbbc5ce6a0d466830aab4b729a0485233378f3f31b4bfe7aa6"
    end
  end

  # No zap stanza required
end
